name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: cargo check --all-targets
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets -- -Dclippy::all -Wclippy::pedantic --deny warnings --no-deps

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tarantool_image_tag: ["3", "2.11", "2.10"]
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - name: Test on ${{ matrix.tarantool_image_tag }} version
        run: cargo test --all-features
        env:
          TARANTOOL_IMAGE_TAG: ${{ matrix.tarantool_image_tag }}

  audit:
    name: Security audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit,cargo-deny
      - run: cargo audit
      - run: cargo deny check advisories
